/*

Advent of Code - 2018

--- Day 1: Chronal Calibration ---

Released under the MIT License <http://opensource.org/licenses/mit-license.php>

*/

;WITH INPUT_D01 AS 
(
    SELECT REPLACE(F.[ITEM], CHAR(10), '') AS FREQ 
      FROM OPENROWSET(BULK 'D:\repos\aoc2018-sql\input\d01.txt', SINGLE_CLOB) INPUT_FILE(FILE_DATA)
     CROSS APPLY dbo.udf_string_split(INPUT_FILE.FILE_DATA, CHAR(13)) F
)
SELECT SUM(CONVERT(INTEGER, FREQ)) AS PART_1
  FROM INPUT_D01
;

WITH INPUT_D01 AS 
(
    SELECT CONVERT(INT, REPLACE(F.[ITEM], CHAR(10), '')) AS FREQ, F.ITEM_NUMBER 
      FROM OPENROWSET(BULK 'D:\repos\aoc2018-sql\input\d01.txt', SINGLE_CLOB) INPUT_FILE(FILE_DATA)
     CROSS APPLY dbo.udf_string_split(INPUT_FILE.FILE_DATA, CHAR(13)) F
), FREQ_CYCLE AS 
(
    SELECT 1 AS NUM, 0 AS ITEM_NUM, 0 AS FREQ
    UNION ALL
    SELECT H2.N,
           D1.ITEM_NUMBER,
           D1.FREQ
      FROM INPUT_D01 D1
     CROSS JOIN pt_stackoverflow.dbo.tbl_numbers H2
     WHERE H2.N <= 500
       AND D1.FREQ <> 0
), FREQUENCIES AS
(
    SELECT SUM(FREQ) OVER (ORDER BY NUM, ITEM_NUM ROWS UNBOUNDED PRECEDING) AS SUM_FREQ, NUM, ITEM_NUM,
           ROW_NUMBER() OVER (ORDER BY NUM, ITEM_NUM) RN
      FROM FREQ_CYCLE
)
SELECT TOP 1 SUM_FREQ AS PART_2
  FROM FREQUENCIES
 GROUP BY SUM_FREQ
HAVING MIN(RN) <> MAX(RN)
 ORDER BY MAX(RN)
;
